const fs = require('fs');
const content = fs.readFileSync('src/pages/MessagesPremium.tsx', 'utf8');
const lines = content.split('\n');

// Find boundaries
let start = -1, end = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i].includes('3ª COLUNA — Dados do contato')) { start = i - 1; }
  if (start > 0 && lines[i].trim() === '})()}' && lines[i-1] && lines[i-1].includes('painelDesprendido')) { end = i; break; }
}
console.log('Replacing lines', start+1, 'to', end+1);

const newSection = [
  "        {/* ══ Multi-panel floating system ══ */}",
  "        {selectedChat && paineis.map(painel => {",
  "          const PAINEL_TITLES: Record<PainelTipo, string> = {",
  "            contato: 'Contato', fluxos: 'Fluxos', observacoes: 'Observações',",
  "          }",
  "          const inp: React.CSSProperties = {",
  "            width: '100%', padding: '8px 10px', borderRadius: 8,",
  "            border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.04)',",
  "            color: '#FFFFFF', fontSize: 13, fontFamily: 'inherit', outline: 'none',",
  "            boxSizing: 'border-box', transition: 'border-color 0.15s',",
  "          }",
  "          const sL = (text: string) => (",
  "            <p style={{ margin: '0 0 8px', fontSize: 10, fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.08em' }}>{text}</p>",
  "          )",
  "          const canalName  = CANAL_META[selectedChat.canal]?.name  ?? selectedChat.canal",
  "          const canalColor = CANAL_META[selectedChat.canal]?.color ?? '#EAB308'",
  "          const canalIcon  = CANAL_META[selectedChat.canal]?.icon  ?? '💬'",
  "          const MOCK_REMARKETING = selectedChat.labels.includes('Cliente') ? 'Campanha Páscoa 2026' : null",
  "",
  "          const panelContent = (() => {",
  "            /* ── Contato ── */",
  "            if (painel.tipo === 'contato') return (",
  "              <div style={{ display: 'flex', flexDirection: 'column' }}>",
  "                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '14px 16px 16px' }}>",
  "                  <div style={{ width: 54, height: 54, borderRadius: '50%', background: 'linear-gradient(135deg, rgba(234,179,8,0.25), #1E293B)', border: '2.5px solid rgba(234,179,8,0.55)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, fontWeight: 700, color: '#EAB308', marginBottom: 8 }}>",
  "                    {(selectedChat.name || 'C')[0].toUpperCase()}",
  "                  </div>",
  "                  <p style={{ margin: '0 0 2px', fontSize: 14, fontWeight: 700, color: '#FFFFFF' }}>{selectedChat.name || 'Sem nome'}</p>",
  "                  <p style={{ margin: '0 0 8px', fontSize: 11, color: '#94A3B8' }}>{selectedChat.phone || 'Sem telefone'}</p>",
  "                  <div style={{ display: 'inline-flex', alignItems: 'center', gap: 5, padding: '3px 10px', borderRadius: 999, background: selectedChat.status === 'online' ? 'rgba(34,197,94,0.08)' : 'rgba(100,116,139,0.10)', border: `1px solid ${selectedChat.status === 'online' ? 'rgba(34,197,94,0.22)' : 'rgba(100,116,139,0.18)'}` }}>",
  "                    <div style={{ width: 6, height: 6, borderRadius: '50%', background: selectedChat.status === 'online' ? '#22C55E' : '#64748B' }} />",
  "                    <span style={{ fontSize: 10, fontWeight: 600, color: selectedChat.status === 'online' ? '#22C55E' : '#64748B' }}>{selectedChat.status === 'online' ? 'Online' : 'Offline'}</span>",
  "                  </div>",
  "                </div>",
  "                <div style={{ padding: '0 14px 14px' }}>",
  "                  {sL('Informações')}",
  "                  <div style={{ borderRadius: 12, border: '1px solid #1E293B', overflow: 'hidden', background: '#0A1628' }}>",
  "                    {([",
  "                      { icon: Phone, label: 'Telefone', value: selectedChat.phone || 'Não informado', special: false },",
  "                      { icon: Mail,  label: 'Email',    value: 'Não informado',                       special: false },",
  "                      { icon: Hash,  label: 'Canal',    value: canalName,                             special: true  },",
  "                    ] as const).map(({ icon: Icon, label, value, special }, i) => (",
  "                      <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px', borderBottom: i < 2 ? '1px solid #1E293B' : 'none' }}>",
  "                        <div style={{ width: 28, height: 28, borderRadius: 7, flexShrink: 0, background: 'rgba(234,179,8,0.07)', border: '1px solid rgba(234,179,8,0.12)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>",
  "                          <Icon style={{ width: 13, height: 13, color: '#EAB308' }} />",
  "                        </div>",
  "                        <div style={{ flex: 1, minWidth: 0 }}>",
  "                          <p style={{ margin: 0, fontSize: 10, color: '#475569', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em' }}>{label}</p>",
  "                          {special ? (",
  "                            <span style={{ fontSize: 12, color: canalColor, fontWeight: 600 }}>{canalIcon} {value}</span>",
  "                          ) : (",
  "                            <p style={{ margin: 0, fontSize: 12, color: value === 'Não informado' ? '#475569' : '#CBD5E1', fontStyle: value === 'Não informado' ? 'italic' : 'normal', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{value}</p>",
  "                          )}",
  "                        </div>",
  "                      </div>",
  "                    ))}",
  "                  </div>",
  "                </div>",
  "                <div style={{ padding: '0 14px 14px' }}>",
  "                  {sL('Tags')}",
  "                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>",
  "                    {selectedChat.labels.length > 0 ? selectedChat.labels.map(label => (",
  "                      <span key={label} style={{ padding: '3px 10px', borderRadius: 999, background: 'rgba(234,179,8,0.12)', border: '1px solid rgba(234,179,8,0.25)', color: '#EAB308', fontSize: 11, fontWeight: 600 }}>{label}</span>",
  "                    )) : <span style={{ fontSize: 12, color: '#475569', fontStyle: 'italic' }}>Nenhuma tag</span>}",
  "                  </div>",
  "                </div>",
  "                <div style={{ padding: '0 14px 14px' }}>",
  "                  {sL('Remarketing')}",
  "                  {MOCK_REMARKETING ? (",
  "                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px', borderRadius: 10, background: 'rgba(234,179,8,0.07)', border: '1px solid rgba(234,179,8,0.20)' }}>",
  "                      <span style={{ fontSize: 14 }}>📣</span>",
  "                      <div><p style={{ margin: '0 0 1px', fontSize: 12, fontWeight: 600, color: '#EAB308' }}>{MOCK_REMARKETING}</p><p style={{ margin: 0, fontSize: 10, color: '#64748B' }}>Campanha ativa</p></div>",
  "                    </div>",
  "                  ) : <p style={{ margin: 0, fontSize: 12, color: '#475569', fontStyle: 'italic' }}>Nenhuma campanha ativa</p>}",
  "                </div>",
  "              </div>",
  "            )",
  "",
  "            /* ── Fluxos ── */",
  "            if (painel.tipo === 'fluxos') return (() => {",
  "              const chatHistory = fluxoHistoryMap[selectedChat.id] ?? []",
  "              const sendFluxo = (fluxo: FluxoEnvio) => {",
  "                const now = new Date()",
  "                setChats(prev => prev.map(c => c.id === selectedChat.id ? { ...c, messages: [...c.messages, { id: Date.now().toString(), senderId: 'user', text: `Fluxo enviado: ${fluxo.nome}`, time: now, isFluxo: true as const }] } : c))",
  "                setFluxoHistoryMap(prev => ({ ...prev, [selectedChat.id]: [{ id: `hist-${Date.now()}`, fluxoId: fluxo.id, nome: fluxo.nome, dataEnvio: now.toLocaleDateString('pt-BR'), horaEnvio: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), status: 'enviado' as const, detalhes: Array.from({ length: fluxo.etapas }, (_, i) => ({ etapa: `Etapa ${i + 1}`, statusEtapa: i === 0 ? 'Enviado' : 'Aguardando' })) }, ...(prev[selectedChat.id] ?? [])] }))",
  "                showToast(`Fluxo \"${fluxo.nome}\" enviado!`)",
  "                setFluxosPanelConfirm(null)",
  "              }",
  "              return (",
  "                <div style={{ padding: '14px' }}>",
  "                  {sL('Fluxos disponíveis')}",
  "                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>",
  "                    {FLUXOS_ENVIO.filter(f => f.ativo).map(fluxo => (",
  "                      <div key={fluxo.id}>",
  "                        {fluxosPanelConfirm === fluxo.id ? (",
  "                          <div style={{ background: 'rgba(234,179,8,0.08)', border: '1px solid rgba(234,179,8,0.25)', borderRadius: 12, padding: '12px 14px' }}>",
  "                            <p style={{ margin: '0 0 10px', fontSize: 12, color: '#CBD5E1', lineHeight: 1.5 }}>Enviar <strong style={{ color: '#EAB308' }}>'{fluxo.nome}'</strong> para <strong style={{ color: '#FFF' }}>{selectedChat.name}</strong>?</p>",
  "                            <div style={{ display: 'flex', gap: 6 }}>",
  "                              <button onClick={() => setFluxosPanelConfirm(null)} style={{ flex: 1, padding: '7px', borderRadius: 8, border: '1px solid #334155', background: 'transparent', color: '#64748B', fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit' }}>Cancelar</button>",
  "                              <button onClick={() => sendFluxo(fluxo)} style={{ flex: 1, padding: '7px', borderRadius: 8, border: 'none', background: '#EAB308', color: '#0F172A', fontSize: 12, fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit' }}>Enviar</button>",
  "                            </div>",
  "                          </div>",
  "                        ) : (",
  "                          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '9px 12px', borderRadius: 10, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}>",
  "                            <div><p style={{ margin: '0 0 1px', fontSize: 12, fontWeight: 600, color: '#E2E8F0' }}>{fluxo.nome}</p><p style={{ margin: 0, fontSize: 10, color: '#475569' }}>{fluxo.etapas} etapas</p></div>",
  "                            <button onClick={() => setFluxosPanelConfirm(fluxo.id)} style={{ padding: '4px 10px', borderRadius: 7, border: 'none', background: '#EAB308', color: '#0F172A', fontSize: 11, fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit' }}>▶ Enviar</button>",
  "                          </div>",
  "                        )}",
  "                      </div>",
  "                    ))}",
  "                  </div>",
  "                  {chatHistory.length > 0 && (",
  "                    <div style={{ marginTop: 16 }}>",
  "                      {sL('Histórico de Fluxos')}",
  "                      {chatHistory.map(item => {",
  "                        const isOpen = fluxoHistoricoDetail === item.id",
  "                        const S = { enviado: { label: 'Enviado', color: '#22C55E', bg: 'rgba(34,197,94,0.10)', dot: '#22C55E' }, em_andamento: { label: 'Em andamento', color: '#F59E0B', bg: 'rgba(245,158,11,0.10)', dot: '#F59E0B' }, falhou: { label: 'Falhou', color: '#F87171', bg: 'rgba(248,113,113,0.10)', dot: '#F87171' } }[item.status]",
  "                        return (",
  "                          <div key={item.id} style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 10, overflow: 'hidden', marginBottom: 5 }}>",
  "                            <button onClick={() => setFluxoHistoricoDetail(isOpen ? null : item.id)} style={{ width: '100%', textAlign: 'left', padding: '9px 12px', background: 'transparent', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, fontFamily: 'inherit' }}>",
  "                              <div><div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 2 }}><Zap style={{ width: 10, height: 10, color: '#EAB308' }} /><span style={{ fontSize: 12, fontWeight: 600, color: '#E2E8F0' }}>{item.nome}</span></div><span style={{ fontSize: 10, color: '#475569' }}>📅 {item.dataEnvio} ⏰ {item.horaEnvio}</span></div>",
  "                              <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>",
  "                                <span style={{ display: 'inline-flex', alignItems: 'center', gap: 3, padding: '2px 7px', borderRadius: 999, background: S.bg, fontSize: 10, fontWeight: 700, color: S.color }}><span style={{ width: 5, height: 5, borderRadius: '50%', background: S.dot, display: 'inline-block' }} />{S.label}</span>",
  "                                <ChevronDown style={{ width: 11, height: 11, color: '#475569', transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.15s' }} />",
  "                              </div>",
  "                            </button>",
  "                            {isOpen && (",
  "                              <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', padding: '8px 12px', display: 'flex', flexDirection: 'column', gap: 5 }}>",
  "                                {item.detalhes.map((d, di) => (",
  "                                  <div key={di} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>",
  "                                    <div style={{ width: 18, height: 18, borderRadius: '50%', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: d.statusEtapa === 'Enviado' ? 'rgba(34,197,94,0.15)' : 'rgba(255,255,255,0.05)', fontSize: 9, fontWeight: 700, color: d.statusEtapa === 'Enviado' ? '#22C55E' : '#475569' }}>{di + 1}</div>",
  "                                    <span style={{ flex: 1, fontSize: 11, color: '#94A3B8' }}>{d.etapa}</span>",
  "                                    <span style={{ fontSize: 10, fontWeight: 600, color: d.statusEtapa === 'Enviado' ? '#22C55E' : '#475569' }}>{d.statusEtapa}</span>",
  "                                  </div>",
  "                                ))}",
  "                              </div>",
  "                            )}",
  "                          </div>",
  "                        )",
  "                      })}",
  "                    </div>",
  "                  )}",
  "                </div>",
  "              )",
  "            })()",
  "",
  "            /* ── Observações ── */",
  "            if (painel.tipo === 'observacoes') return (",
  "              <div style={{ padding: '14px' }}>",
  "                {sL('Observações internas')}",
  "                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>",
  "                  {contatoObs.map(o => (",
  "                    <div key={o.id} style={{ display: 'flex', gap: 10, padding: '10px 12px', borderRadius: 10, background: '#0A1628', border: '1px solid #1E293B' }}>",
  "                      <div style={{ width: 26, height: 26, borderRadius: '50%', flexShrink: 0, background: 'rgba(234,179,8,0.12)', border: '1px solid rgba(234,179,8,0.25)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 700, color: '#EAB308' }}>{o.autor[0].toUpperCase()}</div>",
  "                      <div style={{ flex: 1 }}>",
  "                        <p style={{ margin: '0 0 3px', fontSize: 12, color: '#CBD5E1', lineHeight: 1.5 }}>{o.texto}</p>",
  "                        <p style={{ margin: 0, fontSize: 10, color: '#475569' }}>{o.data}</p>",
  "                      </div>",
  "                    </div>",
  "                  ))}",
  "                  {showNovaObs ? (",
  "                    <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>",
  "                      <textarea value={novaObsTxt} onChange={e => setNovaObsTxt(e.target.value)} rows={3} placeholder=\"Escreva uma observação interna...\" autoFocus",
  "                        style={{ ...inp, resize: 'none', lineHeight: 1.6, padding: '10px 12px' }} />",
  "                      <div style={{ display: 'flex', gap: 6 }}>",
  "                        <button onClick={() => { setShowNovaObs(false); setNovaObsTxt('') }} style={{ flex: 1, padding: '7px', borderRadius: 9, border: '1px solid #1E293B', background: 'transparent', color: '#64748B', fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit' }}>Cancelar</button>",
  "                        <button onClick={() => {",
  "                          if (!novaObsTxt.trim()) return",
  "                          const hoje = new Date()",
  "                          const data = String(hoje.getDate()).padStart(2,'0') + '/' + String(hoje.getMonth()+1).padStart(2,'0') + '/' + hoje.getFullYear() + ' ' + String(hoje.getHours()).padStart(2,'0') + ':' + String(hoje.getMinutes()).padStart(2,'0')",
  "                          setContatoObs(prev => [...prev, { id: Date.now(), texto: novaObsTxt.trim(), autor: 'Maiclei', data }])",
  "                          setNovaObsTxt(''); setShowNovaObs(false); showToast('Observação salva.')",
  "                        }} style={{ flex: 2, padding: '7px', borderRadius: 9, border: 'none', background: '#EAB308', color: '#0F172A', fontSize: 12, fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit' }}>Salvar</button>",
  "                      </div>",
  "                    </div>",
  "                  ) : (",
  "                    <button onClick={() => setShowNovaObs(true)} style={{ width: '100%', padding: '9px', borderRadius: 10, border: '1px dashed rgba(255,255,255,0.10)', background: 'transparent', cursor: 'pointer', fontSize: 12, fontWeight: 600, color: '#475569', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, fontFamily: 'inherit' }}>",
  "                      <Plus style={{ width: 12, height: 12 }} /> Adicionar observação",
  "                    </button>",
  "                  )}",
  "                </div>",
  "              </div>",
  "            )",
  "            return null",
  "          })()",
  "",
  "          const panelEl = (",
  "            <div",
  "              key={painel.id}",
  "              onMouseDown={() => trazParaFrente(painel.id)}",
  "              style={{",
  "                position: 'fixed', left: painel.x, top: painel.y,",
  "                width: 340, zIndex: painel.zIndex,",
  "                background: '#0F172A', border: '1px solid #1E293B', borderRadius: 16,",
  "                boxShadow: '0 20px 60px rgba(0,0,0,0.65), 0 0 0 1px rgba(234,179,8,0.10)',",
  "                display: 'flex', flexDirection: 'column', maxHeight: '80vh',",
  "                animation: 'slideInRight 0.22s cubic-bezier(0.16,1,0.3,1)',",
  "              }}",
  "            >",
  "              <div",
  "                onMouseDown={(e) => handlePainelDragStart(painel.id, e)}",
  "                style={{",
  "                  background: 'linear-gradient(160deg, #0D1E35 0%, #0F172A 100%)',",
  "                  borderBottom: painel.recolhido ? 'none' : '1px solid #1E293B',",
  "                  borderRadius: painel.recolhido ? 16 : '16px 16px 0 0',",
  "                  padding: '9px 12px',",
  "                  display: 'flex', alignItems: 'center', justifyContent: 'space-between',",
  "                  cursor: 'move', userSelect: 'none', flexShrink: 0,",
  "                }}",
  "              >",
  "                <div style={{ display: 'flex', alignItems: 'center', gap: 7, minWidth: 0 }}>",
  "                  <div style={{ display: 'flex', flexDirection: 'column', gap: 2, flexShrink: 0, opacity: 0.4 }}>",
  "                    {[0,1,2].map(i => <div key={i} style={{ width: 12, height: 2, borderRadius: 1, background: '#94A3B8' }} />)}",
  "                  </div>",
  "                  <span style={{ fontSize: 12, fontWeight: 700, color: '#E2E8F0', flexShrink: 0 }}>{PAINEL_TITLES[painel.tipo]}</span>",
  "                  <span style={{ fontSize: 10, color: '#475569', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>— {selectedChat.name}</span>",
  "                </div>",
  "                <div style={{ display: 'flex', gap: 3, flexShrink: 0, marginLeft: 8 }}>",
  "                  <button onClick={(e) => { e.stopPropagation(); toggleRecolhido(painel.id) }} title={painel.recolhido ? 'Expandir' : 'Recolher'}",
  "                    style={{ width: 22, height: 22, borderRadius: 5, border: 'none', background: 'rgba(255,255,255,0.05)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#64748B', fontSize: 11, transition: 'all 0.15s', fontFamily: 'inherit' }}",
  "                    onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.background = 'rgba(234,179,8,0.15)'; (e.currentTarget as HTMLButtonElement).style.color = '#EAB308' }}",
  "                    onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = 'rgba(255,255,255,0.05)'; (e.currentTarget as HTMLButtonElement).style.color = '#64748B' }}",
  "                  >{painel.recolhido ? '▼' : '▲'}</button>",
  "                  <button onClick={(e) => { e.stopPropagation(); fecharPainel(painel.id) }} title=\"Fechar painel\"",
  "                    style={{ width: 22, height: 22, borderRadius: 5, border: 'none', background: 'rgba(255,255,255,0.05)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#64748B', transition: 'all 0.15s' }}",
  "                    onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.background = 'rgba(239,68,68,0.14)'; (e.currentTarget as HTMLButtonElement).style.color = '#F87171' }}",
  "                    onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = 'rgba(255,255,255,0.05)'; (e.currentTarget as HTMLButtonElement).style.color = '#64748B' }}",
  "                  ><X style={{ width: 11, height: 11 }} /></button>",
  "                </div>",
  "              </div>",
  "              {!painel.recolhido && (",
  "                <div style={{ flex: 1, overflowY: 'auto', overflowX: 'hidden' }} className=\"custom-scrollbar\">",
  "                  {panelContent}",
  "                </div>",
  "              )}",
  "            </div>",
  "          )",
  "          return createPortal(panelEl, document.body)",
  "        })}"
].join('\n');

const newLines = [...lines.slice(0, start), ...newSection.split('\n'), ...lines.slice(end + 1)];
fs.writeFileSync('src/pages/MessagesPremium.tsx', newLines.join('\n'));
console.log('Done! Lines', start+1, 'to', end+1, 'replaced with', newSection.split('\n').length, 'lines.');
